# Generated by Django 5.0.2 on 2024-03-15 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
