# Generated by Django 5.0.2 on 2024-03-23 21:46

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_remove_product_additionally_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='additionally',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('None', 'None'), ('Fingerprint identification', 'Fingerprint identification'), ('3G/4G/5G module', '3G/4G/5G module'), ('With Ukrainian layout', 'With Ukrainian layout'), ('With optical drive', 'With optical drive'), ('With backlit keyboard', 'With backlit keyboard'), ('With touch screen', 'With touch screen'), ('Charging from USB', 'Charging from USB'), ('Thunderbolt port', 'Thunderbolt port'), ('Counter-impact housing', 'Counter-impact housing'), ('Supports connection of 2 monitors', 'Supports connection of 2 monitors'), ('With graphic docking station', 'With graphic docking station'), ('Removable battery', 'Removable battery')], max_length=100),
        ),
    ]
